#!/usr/bin/env python3
"""Collect search-improved action targets for distillation.

v25 measured that 10k play is inside this policy's distribution: best-of-K
survival follows failure ~ K^-0.45 with no plateau, so search over the policy's
own samples reaches goal-level survival at K in the hundreds. That makes the
design search-in-the-loop policy iteration -- search finds the rare good
continuation, distillation moves it into the mode, and the next round's search
starts from a better prior.

This is the collect half. At states the policy actually visits, clone the state
into K lanes under common random numbers, sample K continuations, and score each
by whether it survived the horizon. The target for the state is the survival-
weighted distribution over FIRST actions:

    target(a)  proportional to  sum over branches [ survived AND first action = a ]

Soft, not argmax: the v6 work found hard per-state gating discards most of the
corpus, and a single best branch throws away the other K-1 verdicts. Where every
branch survives or every branch dies the target is uninformative and the state is
dropped -- those are the 89% of non-decision-points crn-probe measured, and
training on them just re-teaches the current policy.

Why this is not the BC that failed. v5 distilled go-explore demos and got nothing,
for a diagnosed reason: go-explore's option choices are state-INDEPENDENT by
construction, so there was no state-conditional policy in the data to learn. These
targets are generated by searching over the CURRENT policy at states it actually
reaches, so they are state-conditional by construction, and they improve on the
policy exactly where the policy is improvable.

Writes a .npz of observations, soft targets, and diagnostics.
"""
import argparse
import gzip
import json

import numpy as np
import torch

from ppo_v2 import (
    ActorCriticNetwork,
    checkpoint_control_interval,
    AutoregressiveActionDistribution,
    STICKY_MODEL_ARCHITECTURE,
    StickyActorCriticNetwork,
    load_agent_state,
    packet_observation,
    tensor_observation,
)
from v2_bridge import ParallelEnvBridge

ACTIONS = 18
SATURATION_FRAME = 14400


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('checkpoint')
    parser.add_argument('--out', required=True)
    parser.add_argument('--bank', default='/home/lr/dodgeblock-go-explore-bank-v4/'
                                          'seed-1/search-checkpoint.json.gz')
    parser.add_argument('--workers', type=int, default=8,
                        help='independent trajectories; branches must share a '
                             'worker because the slot table is per worker')
    parser.add_argument('--lanes', type=int, default=32, help='K per trajectory')
    parser.add_argument('--samples', type=int, default=20_000)
    parser.add_argument('--stride', type=int, default=10)
    parser.add_argument('--horizon', type=int, default=120)
    parser.add_argument('--seed', type=int, default=0xD157_111)
    parser.add_argument('--device', default='cuda')
    parser.add_argument('--control-interval', type=int, default=0)
    args = parser.parse_args()

    with gzip.open(args.bank) as handle:
        entries = json.load(handle)['entries']
    pool = [i for i, e in enumerate(entries) if e['frame'] >= SATURATION_FRAME]

    device = torch.device(args.device)
    saved = torch.load(args.checkpoint, map_location=device, weights_only=False)
    network_class = (
        StickyActorCriticNetwork
        if saved.get('model_architecture') == STICKY_MODEL_ARCHITECTURE
        else ActorCriticNetwork
    )
    agent = network_class().to(device)
    load_agent_state(agent, saved['agent'])
    agent.eval()
    interval = args.control_interval or checkpoint_control_interval(saved)

    total = args.workers * args.lanes
    bridge = ParallelEnvBridge(
        args.workers, args.lanes, args.seed,
        target_height=10_000, reward_mode='target', cell_banks=[args.bank],
    )
    slots = np.zeros(total, np.int64)
    rng = np.random.default_rng(0)
    # Lane 0 of each worker carries the real trajectory.
    lead = np.arange(args.workers) * args.lanes

    def act(packet, deterministic_lead=False):
        observation = tensor_observation(packet_observation(packet), device)
        with torch.inference_mode(), torch.autocast(
            device_type=device.type, dtype=torch.bfloat16,
            enabled=device.type == 'cuda',
        ):
            logits, _value, _hazard = agent(observation)
            distribution = AutoregressiveActionDistribution(logits, observation)
            sampled = distribution.sample().cpu().numpy().astype(np.uint8)
            if deterministic_lead:
                mode = distribution.mode().cpu().numpy().astype(np.uint8)
                sampled[lead] = mode[lead]
        return sampled, observation

    observations, targets, spreads = [], [], []
    kept = dropped_uniform = 0

    try:
        while kept < args.samples:
            cells = rng.choice(pool, size=args.workers)
            reset_ids = np.repeat(cells, args.lanes).astype(np.int32)
            packet = bridge.reset(reset_ids)
            held, _ = act(packet, deterministic_lead=True)
            frame = 0
            alive_real = np.ones(args.workers, dtype=bool)
            while alive_real.any() and kept < args.samples:
                if frame % args.stride == 0:
                    packet = bridge.save_slots(slots)
                    packet = bridge.restore_slots(slots)
                    # Snapshot the DECISION state's observation now; `packet`
                    # advances through the branch rollout below and would
                    # otherwise describe a state 120 frames downstream.
                    decision_observation = {
                        key: value.copy()
                        for key, value in packet_observation(packet).items()
                    }
                    first, _ = act(packet)
                    packet = bridge.step(first)
                    alive = ~packet['dones'].astype(bool)
                    branch_held = None
                    for step in range(1, args.horizon):
                        if (step - 1) % interval == 0 or branch_held is None:
                            branch_held, _ = act(packet)
                        actions = branch_held.copy()
                        actions[~alive] = 254
                        packet = bridge.step(actions)
                        alive &= ~packet['dones'].astype(bool)

                    for worker in range(args.workers):
                        if not alive_real[worker]:
                            continue
                        lo = worker * args.lanes
                        block = slice(lo, lo + args.lanes)
                        survived = alive[block]
                        # Uninformative: unanimous verdicts teach nothing.
                        if survived.all() or not survived.any():
                            dropped_uniform += 1
                            continue
                        counts = np.bincount(
                            first[block][survived], minlength=ACTIONS
                        ).astype(np.float32)
                        target = counts / counts.sum()
                        observations.append({
                            key: value[lo].copy()
                            for key, value in decision_observation.items()
                        })
                        targets.append(target)
                        spreads.append(float(survived.mean()))
                        kept += 1

                    packet = bridge.restore_slots(slots)
                    held, _ = act(packet, deterministic_lead=True)

                if frame % interval == 0 and frame % args.stride != 0:
                    held, _ = act(packet, deterministic_lead=True)
                packet = bridge.step(held)
                alive_real &= ~packet['dones'].astype(bool)[lead]
                frame += 1
    finally:
        bridge.close()

    stacked = {
        key: np.stack([o[key] for o in observations])
        for key in observations[0]
    }
    np.savez_compressed(
        args.out,
        targets=np.stack(targets),
        survival_spread=np.array(spreads, np.float32),
        **stacked,
    )
    print(json.dumps({
        'out': args.out,
        'checkpoint': args.checkpoint,
        'samples': kept,
        'dropped_unanimous': dropped_uniform,
        'decision_fraction': round(kept / max(1, kept + dropped_uniform), 4),
        'mean_branch_survival': round(float(np.mean(spreads)), 4),
        'lanes_K': args.lanes,
        'horizon': args.horizon,
        'control_interval': interval,
    }, indent=2))


if __name__ == '__main__':
    main()
