#!/usr/bin/env python3
"""Collect search-improved action targets for distillation.

v25 measured that 10k play is inside this policy's distribution: best-of-K
survival follows failure ~ K^-0.45 with no plateau, so search over the policy's
own samples reaches goal-level survival at K in the hundreds. That makes the
design search-in-the-loop policy iteration -- search finds the rare good
continuation, distillation moves it into the mode, and the next round's search
starts from a better prior.

This is the collect half. At states the policy actually visits, clone the state
into K lanes under common random numbers, sample K continuations, and score each
by whether it survived the horizon. The target for the state is the survival-
weighted distribution over FIRST actions:

    target(a)  proportional to  sum over branches [ survived AND first action = a ]

Soft, not argmax: the v6 work found hard per-state gating discards most of the
corpus, and a single best branch throws away the other K-1 verdicts. Where every
branch survives or every branch dies the target is uninformative and the state is
dropped -- those are the 89% of non-decision-points crn-probe measured, and
training on them just re-teaches the current policy.

Why this is not the BC that failed. v5 distilled go-explore demos and got nothing,
for a diagnosed reason: go-explore's option choices are state-INDEPENDENT by
construction, so there was no state-conditional policy in the data to learn. These
targets are generated by searching over the CURRENT policy at states it actually
reaches, so they are state-conditional by construction, and they improve on the
policy exactly where the policy is improvable.

Writes a .npz of observations, soft targets, and diagnostics.
"""
import argparse
import gzip
import json
import sys
import time

import numpy as np
import torch

from ppo_v2 import (
    ActorCriticNetwork,
    checkpoint_control_interval,
    AutoregressiveActionDistribution,
    STICKY_MODEL_ARCHITECTURE,
    StickyActorCriticNetwork,
    load_agent_state,
    focus_action_mask,
    packet_observation,
    tensor_observation,
)
from v2_bridge import ParallelEnvBridge

ACTIONS = 18
SATURATION_FRAME = 14400


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('checkpoint')
    parser.add_argument('--out', required=True)
    parser.add_argument('--bank', default='/home/lr/dodgeblock-go-explore-bank-v4/'
                                          'seed-1/search-checkpoint.json.gz')
    parser.add_argument('--workers', type=int, default=8,
                        help='independent trajectories; branches must share a '
                             'worker because the slot table is per worker')
    parser.add_argument('--lanes', type=int, default=32, help='K per trajectory')
    parser.add_argument('--samples', type=int, default=20_000)
    parser.add_argument('--stride', type=int, default=10)
    parser.add_argument('--horizon', type=int, default=120)
    parser.add_argument('--seed', type=int, default=0xD157_111)
    parser.add_argument('--device', default='cuda')
    parser.add_argument('--control-interval', type=int, default=0)
    parser.add_argument('--max-hours', type=float, default=6.0,
                        help='stop and write what has been collected; a silent '
                             'run that never finishes is worse than a short one')
    parser.add_argument('--progress-every', type=int, default=250)
    args = parser.parse_args()

    with gzip.open(args.bank) as handle:
        entries = json.load(handle)['entries']
    pool = [i for i, e in enumerate(entries) if e['frame'] >= SATURATION_FRAME]

    device = torch.device(args.device)
    saved = torch.load(args.checkpoint, map_location=device, weights_only=False)
    network_class = (
        StickyActorCriticNetwork
        if saved.get('model_architecture') == STICKY_MODEL_ARCHITECTURE
        else ActorCriticNetwork
    )
    agent = network_class().to(device)
    load_agent_state(agent, saved['agent'])
    agent.eval()
    interval = args.control_interval or checkpoint_control_interval(saved)

    total = args.workers * args.lanes
    bridge = ParallelEnvBridge(
        args.workers, args.lanes, args.seed,
        target_height=10_000, reward_mode='target', cell_banks=[args.bank],
    )
    # Slot tables live inside each env-server worker. Saving every lane to slot
    # 0 overwrites the lead snapshot with the last branch lane in that worker.
    # Save lane i to slot i, then restore all lanes from slot 0 so each branch
    # search starts from the policy trajectory's lead state under common futures.
    branch_slots = np.tile(np.arange(args.lanes, dtype=np.int64), args.workers)
    lead_slots = np.zeros(total, np.int64)
    rng = np.random.default_rng(0)
    # Lane 0 of each worker carries the real trajectory.
    lead = np.arange(args.workers) * args.lanes

    def lead_actions(actions):
        return np.repeat(actions[lead], args.lanes).astype(np.uint8)

    def act(packet, deterministic_lead=False):
        observation = tensor_observation(packet_observation(packet), device)
        with torch.inference_mode(), torch.autocast(
            device_type=device.type, dtype=torch.bfloat16,
            enabled=device.type == 'cuda',
        ):
            logits, _value, _hazard = agent(observation)
            distribution = AutoregressiveActionDistribution(logits, observation)
            sampled = distribution.sample().cpu().numpy().astype(np.uint8)
            if deterministic_lead:
                mode = distribution.mode().cpu().numpy().astype(np.uint8)
                sampled[lead] = mode[lead]
        return sampled, observation

    observations, targets, spreads = [], [], []
    kept = dropped_uniform = dropped_illegal_rows = 0
    illegal_mass = 0.0
    started = time.monotonic()
    last_report = 0

    def elapsed_hours():
        return (time.monotonic() - started) / 3600.0

    try:
        while kept < args.samples and elapsed_hours() <= args.max_hours:
            cells = rng.choice(pool, size=args.workers)
            reset_ids = np.repeat(cells, args.lanes).astype(np.int32)
            packet = bridge.reset(reset_ids)
            held, _ = act(packet, deterministic_lead=True)
            held = lead_actions(held)
            frame = 0
            alive_real = np.ones(args.workers, dtype=bool)
            while alive_real.any() and kept < args.samples:
                if elapsed_hours() > args.max_hours:
                    break
                if frame % args.stride == 0:
                    packet = bridge.save_slots(branch_slots)
                    packet = bridge.restore_slots(lead_slots)
                    # Snapshot the DECISION state's observation now; `packet`
                    # advances through the branch rollout below and would
                    # otherwise describe a state 120 frames downstream.
                    decision_observation = {
                        key: value.copy()
                        for key, value in packet_observation(packet).items()
                    }
                    decision_tensor = tensor_observation(decision_observation, device)
                    with torch.inference_mode():
                        focus_ok = focus_action_mask(decision_tensor)[..., 1]
                    focus_ok = focus_ok.cpu().numpy()
                    legal_actions = np.ones((args.workers, ACTIONS), bool)
                    for w in range(args.workers):
                        legal_actions[w, 9:] = bool(focus_ok[w * args.lanes])

                    first, _ = act(packet)
                    packet = bridge.step(first)
                    alive = ~packet['dones'].astype(bool)
                    branch_held = None
                    for step in range(1, args.horizon):
                        if (step - 1) % interval == 0 or branch_held is None:
                            branch_held, _ = act(packet)
                        actions = branch_held.copy()
                        actions[~alive] = 254
                        packet = bridge.step(actions)
                        alive &= ~packet['dones'].astype(bool)

                    for worker in range(args.workers):
                        if not alive_real[worker]:
                            continue
                        lo = worker * args.lanes
                        block = slice(lo, lo + args.lanes)
                        survived = alive[block]
                        # Uninformative: unanimous verdicts teach nothing.
                        if survived.all() or not survived.any():
                            dropped_uniform += 1
                            continue
                        counts = np.bincount(
                            first[block][survived], minlength=ACTIONS
                        ).astype(np.float32)
                        # Codex: the generator should not emit mass the policy
                        # cannot legally place. Drop illegal actions here rather
                        # than leaving it to the trainer's guard, and count the
                        # disagreements so the cause stays visible instead of
                        # being silently absorbed.
                        illegal = counts * (~legal_actions[worker])
                        if illegal.sum() > 0:
                            dropped_illegal_rows += 1
                            illegal_mass += float(illegal.sum() / counts.sum())
                            counts = counts * legal_actions[worker]
                        if counts.sum() <= 0:
                            dropped_uniform += 1
                            continue
                        target = counts / counts.sum()
                        observations.append({
                            key: value[lo].copy()
                            for key, value in decision_observation.items()
                        })
                        targets.append(target)
                        spreads.append(float(survived.mean()))
                        kept += 1

                    if kept - last_report >= args.progress_every:
                        last_report = kept
                        rate = kept / max(1e-9, elapsed_hours())
                        remaining = (args.samples - kept) / max(1e-9, rate)
                        print(f'[collect] {kept}/{args.samples} samples '
                              f'{elapsed_hours():.2f}h elapsed '
                              f'{rate:.0f}/h eta {remaining:.2f}h '
                              f'decision_frac '
                              f'{kept / max(1, kept + dropped_uniform):.3f}',
                              file=sys.stderr, flush=True)

                    packet = bridge.restore_slots(lead_slots)
                    held, _ = act(packet, deterministic_lead=True)
                    held = lead_actions(held)

                if frame % interval == 0 and frame % args.stride != 0:
                    held, _ = act(packet, deterministic_lead=True)
                    held = lead_actions(held)
                packet = bridge.step(held)
                alive_real &= ~packet['dones'].astype(bool)[lead]
                frame += 1
    finally:
        bridge.close()

    stacked = {
        key: np.stack([o[key] for o in observations])
        for key in observations[0]
    }
    np.savez_compressed(
        args.out,
        targets=np.stack(targets),
        survival_spread=np.array(spreads, np.float32),
        **stacked,
    )
    print(json.dumps({
        'out': args.out,
        'checkpoint': args.checkpoint,
        'samples': kept,
        'dropped_unanimous': dropped_uniform,
        'decision_fraction': round(kept / max(1, kept + dropped_uniform), 4),
        'mean_branch_survival': round(float(np.mean(spreads)), 4),
        'hours': round(elapsed_hours(), 3),
        'hit_time_limit': elapsed_hours() > args.max_hours,
        'rows_with_illegal_mass': dropped_illegal_rows,
        'mean_illegal_mass_when_present': (
            round(illegal_mass / dropped_illegal_rows, 4)
            if dropped_illegal_rows else 0.0),
        'lanes_K': args.lanes,
        'horizon': args.horizon,
        'control_interval': interval,
    }, indent=2))


if __name__ == '__main__':
    main()
